import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Atque
                tempora doloribus ipsum ex tempore officiis eaque deleniti
                doloremque quaerat impedit, soluta facilis, blanditiis ad.
                Praesentium sunt magnam eum. Numquam, voluptates?
            </main>
        </>
    );
}
